//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Citizen.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Tracking.
        /// </summary>
        internal static string ContactTracking {
            get {
                return ResourceManager.GetString("ContactTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        internal static string EnumMaritalDivorced {
            get {
                return ResourceManager.GetString("EnumMaritalDivorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string EnumMaritalMarried {
            get {
                return ResourceManager.GetString("EnumMaritalMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string EnumMaritalSingle {
            get {
                return ResourceManager.GetString("EnumMaritalSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widow.
        /// </summary>
        internal static string EnumMaritaWidow {
            get {
                return ResourceManager.GetString("EnumMaritaWidow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City female.
        /// </summary>
        internal static string EnumPhysicalContact_City_Female {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_City_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City male.
        /// </summary>
        internal static string EnumPhysicalContact_City_Male {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_City_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daughter.
        /// </summary>
        internal static string EnumPhysicalContact_Daughter {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aunt.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Aunt {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Aunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Father {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrandFather.
        /// </summary>
        internal static string EnumPhysicalContact_Family_GrandFather {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_GrandFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrandMother.
        /// </summary>
        internal static string EnumPhysicalContact_Family_GrandMother {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_GrandMother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husband.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Husband {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Mother {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nephew.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Nephew {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Nephew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niece.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Niece {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Niece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Son {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncle.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Uncle {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Uncle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wife.
        /// </summary>
        internal static string EnumPhysicalContact_Family_Wife {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_Wife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family worker.
        /// </summary>
        internal static string EnumPhysicalContact_Family_worker {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Family_worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend female.
        /// </summary>
        internal static string EnumPhysicalContact_Friend_Female {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Friend_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend male.
        /// </summary>
        internal static string EnumPhysicalContact_Friend_Male {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Friend_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbor female.
        /// </summary>
        internal static string EnumPhysicalContact_Neighbor_Female {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Neighbor_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbor male.
        /// </summary>
        internal static string EnumPhysicalContact_Neighbor_Male {
            get {
                return ResourceManager.GetString("EnumPhysicalContact_Neighbor_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in attempt failed. Please try again later..
        /// </summary>
        internal static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT TRACKING.
        /// </summary>
        internal static string Menu_largeButtons_ContactTracking {
            get {
                return ResourceManager.GetString("Menu_largeButtons_ContactTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COWRIE.
        /// </summary>
        internal static string Menu_largeButtons_Cowrie {
            get {
                return ResourceManager.GetString("Menu_largeButtons_Cowrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string Menu_largeButtons_Map {
            get {
                return ResourceManager.GetString("Menu_largeButtons_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid e-mail.
        /// </summary>
        internal static string PlaceHolderValidEmail {
            get {
                return ResourceManager.GetString("PlaceHolderValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Top Up.
        /// </summary>
        internal static string QuickTopUp {
            get {
                return ResourceManager.GetString("QuickTopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER ACCOUNT.
        /// </summary>
        internal static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegisterHdr {
            get {
                return ResourceManager.GetString("RegisterHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been successfull. Please log in..
        /// </summary>
        internal static string RegistratationSuccess {
            get {
                return ResourceManager.GetString("RegistratationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.  Please try again later..
        /// </summary>
        internal static string RegistrationFailure {
            get {
                return ResourceManager.GetString("RegistrationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select birth date.
        /// </summary>
        internal static string SelectBirthDate {
            get {
                return ResourceManager.GetString("SelectBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select contact type.
        /// </summary>
        internal static string SelectContactType {
            get {
                return ResourceManager.GetString("SelectContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Home, Stay Safe.
        /// </summary>
        internal static string StayHomeSafe {
            get {
                return ResourceManager.GetString("StayHomeSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were near :.
        /// </summary>
        internal static string YouCanInCloseContactWith {
            get {
                return ResourceManager.GetString("YouCanInCloseContactWith", resourceCulture);
            }
        }
    }
}
